sudo: required
services:
  -docker

before_install:
  - docker build -t samsilverstein/docker-react-practice -f dockerfile.dev . 

script:
 - docker run -e CI=true samsilverstein/docker-react-practice npm run test